### ISSUE TITLE
Can't fold and unfold headings

### ISSUE THREAD

**Issue by msenca** [roam-unofficial/roam-toolkit#125]
Hi,

It seems like the "Toggle Fold Block" does not work when the block is a header. Is this solvable?

The vim-navigation is create. Thank you!

**Comment by butterywombat** [comment]
Folding doesn't work for me in linked references either (although it kind of works if I mouseover the block until the fold arrow appears, then hit z). Not sure if this should be a new issue, thought I'd tag along :)

**Comment by tntmarket** [comment]
Yeah, https://github.com/roam-unofficial/roam-toolkit/issues/118 was fixed earlier, but hasn't been released yet
