### ISSUE TITLE
Feature Request - Fuzzy Date with Reschedule

### ISSUE THREAD

**Issue by Itshalffull** [roam-unofficial/roam-toolkit#136]
I love the fuzzy date feature! 

One frequent use case I use it for is rescheduling.  However, this requires two steps:

1. Deleting the current date.
2. Entering the new date with fuzzy date.

I would love the option to use a seperate delimiter than the fuzzy date functionality which allows me to reschedule instead of adding a date.  So of I entered say +thursday+ it would do two things:

1. Find any existing date links on the line I'm currently on, and delete them.
2. Replace +thursday+ with the correct date link as happens currently with the fuzzy date tool.

This would save me a ton of time!

**Comment by Stvad** [comment]
this actually exists already, but not documented well - see #40
