### ISSUE TITLE
Feature request: open random page

### ISSUE THREAD

**Issue by benwf** [roam-unofficial/roam-toolkit#146]
It would be awesome if there was a keyboard shortcut to open a random page.

I know [there's a JS bookmarklet for opening on the All Pages page](https://forum.roamresearch.com/t/what-would-be-your-top-3-tips-for-beginners/255/9) to open a random page, but it's pretty slow as we first need to navigate to All Pages (which is relatively slow with _lots_ of pages).

[Here's some background information on "why."](https://fortelabs.co/blog/randomnote-web/)

Thank you for considering!

**Comment by Stvad** [comment]
`roamAlphaAPI` would be useful here to obtain the list of all pages.  
or maybe we can generate a random uuid and pick a page based on that..

**Comment by tntmarket** [comment]
I created a hacky solution by just picking a random link on "All Pages".

I think it's kinda nice for gardening, cause you can just open like ~20 random pages in your sidebar, and then proceed to gardening them:

![random page](https://user-images.githubusercontent.com/1150079/89116338-f9fb8b80-d447-11ea-9938-88de8e281313.gif)

**Comment by benwf** [comment]
@tntmarket this is awesome. Can you share the code already? I like that you specifically mention "gardening purposes".

**Comment by tntmarket** [comment]
Oh @benwf you can check out the linked PR for the code, and follow the "developing" steps in the Readme if you want to try this earlier 😃

**Comment by benwf** [comment]
@tntmarket oh I will! Thank you :)
