### ISSUE TITLE
Vim - Toggle Fold Block - Ceases to work with header formatting

### ISSUE THREAD

**Issue by yet-another-tim** [roam-unofficial/roam-toolkit#150]
When using the Vim "Toggle Fold Block" feature, folding works if the block being folded has no header formatting. With header formatting, folding doesn't work. Other formatting like bold and italic seem to work fine.

FWIW, 
Browser - Brave 1.11.104
OS - Pop_OS 20.04

(Thanks for the extension, I'm loving it!)

**Comment by Stvad** [comment]
#125 this is already fixed in the dev version. been busy recently - need to make a release
