### ISSUE TITLE
FuzzyDate activation issue (David)

### ISSUE THREAD

**Issue by Stvad** [roam-unofficial/roam-toolkit#152]
Hi. I really like Roam-Toolkit. One thing I can’t get to work, though, is fuzzy dates.

 

If I type ;fri; it remains ;fri;

If I type ;next friday; it remains ;next friday;

 
![image](https://user-images.githubusercontent.com/81347/90209509-72474280-dda0-11ea-8ef0-80dda75bfe8c.png)

 

I have the option selected.

A close up of a logo

![image](https://user-images.githubusercontent.com/81347/90209520-7b381400-dda0-11ea-9e5b-88558326a0d4.png)

 

And I confirm the guard symbol is ;

![image](https://user-images.githubusercontent.com/81347/90209539-8723d600-dda0-11ea-9d9c-9ca5f6032588.png)

 

What else might cause this not to work?

 

Roam-Toolkit is the only extension I have active.

I have no Javascript in my Roam.

**Comment by eatondpe** [comment]
Thanks for responding, Vlad. Here is the additional information you requested.

Machine:  Laptop
Browser:  Microsoft Edge-Chromium
OS:  Windows 10
Toolkit Version:  0.4.0
Keyboard Layout:  QWERTY

I was about to try changing the guard symbol, so I opened the browser console and first wanted to recreate the issue. However, what wasn't working yesterday, is working fine today. And I haven't changed anything.

If I do experience this again, I'll looking for errors in the console.  But this appears to no longer be a problem.

Thanks!

**Comment by Stvad** [comment]
@eatondpe great to hear it works now :)
