### ISSUE TITLE
Can we disable the warning for deleting referenced blocks?

### ISSUE THREAD

**Issue by tntmarket** [roam-unofficial/roam-toolkit#163]
I sometimes cut/paste blocks to move them around. Can we optionally disable this warning?

![Screen Shot 2020-09-27 at 4 05 20 PM](https://user-images.githubusercontent.com/1150079/94378068-3f040d00-00db-11eb-9ed6-8cabedb532c9.png)

**Comment by tntmarket** [comment]
Oops I meant to file this in the actual roam reasearch github, my bad lol

**Comment by Stvad** [comment]
😄 that said we can probably block alerts or something :p. I like the idea of this popup though, but I can see it being annoying for cut & paste
