### ISSUE TITLE
Fold/Unfold stopped working

### ISSUE THREAD

**Issue by ivanddm** [roam-unofficial/roam-toolkit#170]
Hi there,

One of the Vim shortcuts I use the most is to fold/unfold with `z`. However, I just noticed that it stopped working today (probably with the latest update of the extension?). The other Vim shortcuts seem to be working fine, though.

I would appreciate if you can look into this issue. Thanks in advance.

**Comment by msenca** [comment]
Hi,

The issue was fixed in [167](https://github.com/roam-unofficial/roam-toolkit/pull/167#issue-501193328). It works again in version 0.4.4, update your extension and you should be good!

**Comment by ivanddm** [comment]
Great, thanks!
