### ISSUE TITLE
Why does putting once a day between semi-colons replace it with a bi-link to the current day?

### ISSUE THREAD

**Issue by MaskyS** [roam-unofficial/roam-toolkit#172]
inputting `;once a day;` replaces it with `[[October 21st, 2020]]`. Why?

Same thing happens no matter what else is in between. i.e. `; oh, once a day;` also gets replaced

**Comment by maggiedelano** [comment]
It's called fuzzy date; it is helpful to allow you to quickly get a date in the correct form. Like ;today; ;one week;, etc.

If you don't like it you can disable it in the Roam Toolkit menu; scroll down and uncheck "Fuzzy Date." You can also choose which character is used as the "guard" symbol (currently ;).

**Comment by MaskyS** [comment]
Fuzzy date's great, but I don't understand why it's triggered even when there isn't an exact match, i.e. `;hello this is text but it doesn't matter once a day;`.

**Comment by Stvad** [comment]
It operates on best effort basis :) It tries to interpret whatever you put between guard symbols as date
