### ISSUE TITLE
SRS parser thrown off by blocks with dates?

### ISSUE THREAD

**Issue by cansar** [roam-unofficial/roam-toolkit#186]
I'm having an issue where for certain blocks interval and factor get updated but dates get appended instead of replaced. The key seems to be having blocks with 2 dates in them, e.g. `From [[November 6th, 2020]] until [[November 9th, 2020]].`

Applying ctrl-shift-1 multiple times results in `From [[November 6th, 2020]] until [[November 9th, 2020]]. [[[[interval]]:1.0]] [[[[factor]]:1.90]] [[December 11th, 2020]] [[December 10th, 2020]] [[December 10th, 2020]]` and so forth.

**Comment by cansar** [comment]
Actually even using one date seems to affect things. E.g.
`Today's date is [[December 9th, 2020]].
turns into
`Today's date is [[December 15th, 2020]]. [[[[interval]]:5.2]] [[[[factor]]:2.50]]`
and that date keeps being bumped after that.

**Comment by Stvad** [comment]
SRS parser treats the first date it finds as the "next day to schedule review for". there no way to distinguish an arbitrary date and srs review date atm.  I'd recommend creating a sub-block with SRS metadata in this case
