### ISSUE TITLE
Considering the implementation of Ebisu algorithm

### ISSUE THREAD

**Issue by Positron010** [roam-unofficial/roam-toolkit#191]
Hey, and thanks for your hard work!

Can you please consider implementing [Ebisu](https://github.com/fasiha/ebisu) algorithm again? At least giving the user the choice to use it. 

The majority of Spaced Repetition programs implement the SM-2 algorithm, or with slight modifications, and there isn't a public-ready application that implements Ebisu yet as far as I know. I think implementing it, at least for me will be an attractive point. The author of Ebisu is also active on Github and kindly responses to any doubs and questions.

Thanks! @Stvad

_Originally posted by @Positron010 in https://github.com/roam-unofficial/roam-toolkit/issues/1#issuecomment-777870376_

**Comment by Stvad** [comment]
Apologies for lack of the reply, I'm not able to dedicate much time to Roam Toolkit these days 🙁.  (mainly focusing on https://roam.garden/)  
I'm using Roam Toolkit SRS a lot myself, I've seen a few interesting advances in SRS for Roam though. 
https://github.com/aidam38/roamsr provides a nice review experience and I was thinking about integrating with it when I get some time.

Maybe open a request for https://github.com/aidam38/roamsr in case Adam would be able to look into it sooner?
