### ISSUE TITLE
Increase / decrease of numbers, dates: ideas and discussion

### ISSUE THREAD

**Issue by PiotrSss** [roam-unofficial/roam-toolkit#2]
Changing values +/- 1 with shortcuts.
Inspired by https://github.com/rmaksim/Sublime-Text-2-Inc-Dec-Value

For dates it might include something more, for example add value after date and press some shortcut to calculate new date
[[January 29th, 2020]]+7d -> [[February 5th, 2020]]
[[January 29th, 2020]]-6d -> [[January 23rd, 2020]]
[[January 29th, 2020]]+3w -> [[February 19th, 2020]]
[[January 29th, 2020]]+4m -> [[May 29th, 2020]]

Or we can create separate feature for calculating dates.

**Comment by Stvad** [comment]
I think it’d be neat if you could also do inc/dec by week/month/year. for the date calculus I think we can cover that (or similar functionality) by integrating fuzzyDate stuff

**Comment by panpiotrs** [comment]
With +/-1 day/month/year I agree, placing the cursor on one of these places [[Jan|uary 29|th, 20|20]] could inc/dec only that. But inc/dec by week would require additional shortcut or you have something else in mind?

**Comment by Stvad** [comment]
Yeah, would probably require a separate shortcut 🤔 which is sad, as the week would probably be something that I'd personally use more often then other options.

**Comment by Stvad** [comment]
added shortcuts for week at some point. I think the use case for adding dates is mostly covered by fuzzy date. Closing this for now
