### ISSUE TITLE
Fuzzy Date doesn't work anymore

### ISSUE THREAD

**Issue by edoarad** [roam-unofficial/roam-toolkit#206]
I don't see any Fuzzy Date behavior. 
I've tried multiple guard symbols, and other toolkit features seem to work well.

I'm using Chrome at Windows.

**Comment by Stvad** [comment]
hmm, are you using any other extensions that may interfere? can you try on a ~fresh roam db (or with roam/js plugins disabled) and in incognito mode?

**Comment by edoarad** [comment]
Tried some things, but it seems to be working now. Not sure what happened 😊

**Comment by Stvad** [comment]
ok, good to hear it works now :)
