### ISSUE TITLE
Some features work; some do not

### ISSUE THREAD

**Issue by dutchanton** [roam-unofficial/roam-toolkit#210]
I use version 0.5.3 in Chrome (latest update).

Some features work (e.g. Spaced Repetition, Block Manipulation). 

Others do not (e.g. Fuzzy Dates, Navigation), even though I have checked them.

**Comment by Stvad** [comment]
Can you elaborate on what exactly you are trying to do and what happens instead? What other roam plugins do you have installed?

**Comment by dutchanton** [comment]
When I try to use Fuzzy date, I type this: **;sun**, but then nothing happens. Navigation does not work either. I have tried both features with different shorcuts.

As for other plugins, I use the RoamJS [Query Builder](https://roamjs.com/extensions/query-builder). I believe that at one point I installed a suggested collection of RoamJS extensions. However, I do not know how and where to find those installations.

**Comment by Stvad** [comment]
For the fuzzy date: you need to type `;sun;` (with closing semicolon) for it to work.  

Please elaborate on what navigation feature you're trying to use and what happens instead. There is a known issue with "go to today's page" being broken after some version of Chrome.  

You can find all your `roam/js` extensions by looking at the `roam/js` page (and backlinks to it). I'd recommend disabling things you do not use

**Comment by dutchanton** [comment]
The fuzzy date works now. Great! Very handy.

Go to today's page indeed does not work in my Chrome, but it does work in Vivaldi. 

Thanks for your help.
