### ISSUE TITLE
Fuzzy date formats which don't work as expected

### ISSUE THREAD

**Issue by richardtkemp** [roam-unofficial/roam-toolkit#43]
Fuzzy date is fantastic, but here are some examples which didn't do what I hoped they would. Format of the following is input followed by output.

- start of next year [[April 7th, 2021]]
- 2021 ;2021; 
- end of may [[May 1st, 2020]]
- last may [[May 1st, 2020]]
- 2 wk ;2 wk; 
- 1 mth ;1 mth;
- jun 1 - 5 days [[June 1st, 2020]] 
- 1 jun -5 days [[April 12th, 2020]]

**Comment by Stvad** [comment]
It relies on https://github.com/wanasit/chrono for actual fuzzy parsing, so I believe it'd be more appropriate to direct this request there :)

**Comment by richardtkemp** [comment]
Will do, thanks.
