### ISSUE TITLE
Dynamic templates

### ISSUE THREAD

**Issue by Stvad** [roam-unofficial/roam-toolkit#45]
15 hours ago
@Vladyslav Sitalo and others, we really should get templates added to Roam Toolkit, since people are wasting a lot of time hacking all kinds of things. It shouldn’t be that hard… I guess one thing is just adding the config UI for adding templates and triggers (it could be a single daily template with a hard-coded trigger, but if we’re going to do it, we might as well do it correctly?) :slightly_smiling_face: The second thing is figuring out how to make the template dynamic - mainly with dates (anything else?)… I wonder if just letting people embed things like ;today; ;tomorrow; etc would be enough? This should also let you generate a weekly template with ;monday; ;tuesday; etc. And finally we need to insert it onto the page - I think we already have the ability to insert a bunch of blocks properly, but I would have to look at our code to see the exact procedure…
does this sound about right? Anyone want to share the work?

Vladyslav Sitalo  14 hours ago
I feel like there are a whole bunch of template languages out there, I think we should just integrate with one of them for dynamic templates

Stian Håklev  14 hours ago
Yeah, but we basically need to provide variables, and since we already have a built-in dynamic way of specifying dates (which is the only thing we can imagine people wanting to make dependent) we would want to reuse that I think

Vladyslav Sitalo  3 hours ago
I can envision all kind of substitutions.
name of the current date of the week
random number
polling things from some api
things you need to fill in on executing the template

Vladyslav Sitalo  3 hours ago
etc

Vladyslav Sitalo  2 hours ago
polling things from the Datalog using the js api

Stian Håklev  1 hour ago
Good points, although I think starting with date-related stuff and a random id would be a good beginning. (We could also have “link to a random page” if we can get that from Datalog somehow).

**Comment by ryanguill** [comment]
I think this could be quite useful if configurable - and although you could do a lot of things that would make it great, dont let great stop you from shipping something good. you can always iterate on it later.

**Comment by Stvad** [comment]
implemented natively and in Roam42 now
