### ISSUE TITLE
Keyboard shortcut to focus cursor

### ISSUE THREAD

**Issue by kalenjordan** [roam-unofficial/roam-toolkit#47]
A keyboard shortcut to focus the cursor - possibly Command+Enter?

How it works currently:
1. Search for a page using Command+U
2. Select a page using arrow keys and Enter
3. You have to use the mouse to click before you can start typing

How I'd like it to work:
1. Search for a page using Command+U
2. Select a page using arrow keys and Enter
3. Begin typing using this keyboard shortcut.

**Comment by teodorlu** [comment]
> it is not possible to find a page or create a page and then start typing without using the mouse

I don't think I follow. Didn't you just explain how to do that with? Caveat: I'm on Linux, where control+U takes me to the search bar.

**Comment by kalenjordan** [comment]
I updated the initial post to hopefully make it more clear.

**Comment by teodorlu** [comment]
Ah, I see what you mean now. I agree, that would help create pages faster.

**Comment by maxcodes** [comment]
I played around trying to implement this, but couldn't quite figure it out. Simulating a click using `element.click()` doesn't work. I assume we'd need to fiddle with how React handles events internally, but given the weird compression that Roam uses, I doubt we'll be able to reverse engineer which component does what...

If anyone has any pointers as to how to achieve this, I'd be more than happy to try implementing it

**Comment by Stvad** [comment]
the functionality to create new block already exists in `Roam` objects. and there is also #24 PR to improve on that. 

I'm not quite sure how to detect that we've just created a new page though

**Comment by maxcodes** [comment]
Can't we just detect the "Untitled" text?

Max Holzheu

**Comment by Stvad** [comment]
My understanding is that this exists natively in Roam now - `Cmd-Enter` would get you to the first block
