### ISSUE TITLE
Feature request: Lazy dates

### ISSUE THREAD

**Issue by antonylewis** [roam-unofficial/roam-toolkit#60]
Inspired by an email tool I used called Sanebox:
1d = in 1 day 2d = in 2 days (nd = in n days).  If today is Wednesday, 1d would return Thursday.
1w, 2w, nw = in 1 week etc.  If today is Wednesday, 1w would return next Wednesday.
1m, 2m, nm = in 1 month etc. If today is the 1st of the month, 1m would return the first of next month.  Needs small additional logic for 30th, 31st, and leap years.
1y, 2y, ny = in 1 year etc.  If today is 18 May 2020, 1y would return 18 May 2021.  Needs small additional logic for leap years.

**Comment by Stvad** [comment]
I assume this is for Fuzzy Date. I'd like that too, FuzzyDate uses https://github.com/wanasit/chrono/ as the underlying implementation to actually parse things though. So this would be a more appropriately directed as an issue on that repo.

That said you don't have to type things like `in 1 day` a shorter version of `1 day` or `2 years` would work too

**Comment by antonylewis** [comment]
Thanks, good to know.

**Comment by Stvad** [comment]
I'd argue it's "natural written language" 😛
