### ISSUE TITLE
SRS: New date is calculated based on the date in the block (vs today). Consider if it's the desired behavior

### ISSUE THREAD

**Issue by Stvad** [roam-unofficial/roam-toolkit#66]
I have arguments for both 🤔

**Comment by Itshalffull** [comment]
IMO should be calculated based on current date.  If I don't do it for a few days the scheduling gets totally messed up.  This is also AFAICT how all other SRS apps do it.

**Comment by Stvad** [comment]
Yeah, I mostly don't miss the reviews, but I imagine it's weird if you did and the calculate from the past date

**Comment by houshuang** [comment]
Yes, was actually just going to post this. It should definitively be based on today's date.

**Comment by Stvad** [comment]
Changed it to be based on today
