### ISSUE TITLE
Live Preview is not loading starting today 

### ISSUE THREAD

**Issue by Stvad** [roam-unofficial/roam-toolkit#86]
![image](https://user-images.githubusercontent.com/81347/85362789-35637b80-b4d4-11ea-8a15-f9b79edba3fb.png)

https://roamresearch.slack.com/archives/CTAE9JC2K/p1592886031336500

**Comment by sml920505** [comment]
hi Stvad, I use this feature everyday. It is the best feature in roam .
Do you have any plan to Fix it?

**Comment by Stvad** [comment]
it seems like the latest updates to Roam make currently employed approach inoperable :(  
[x-frame-options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) is set to “DENY” which prevents things from being loaded in Iframe

**Comment by Stvad** [comment]
Roam team has deployed an update and this should work again!
