### ISSUE TITLE
Consider including roam-navigator

### ISSUE THREAD

**Issue by mgsloan** [roam-unofficial/roam-toolkit#91]
Hi!  I've written a [fairly extensive extension, augmenting Roam with keyboard driven navigation](https://github.com/mgsloan/roam-navigator).  When I mentioned to [Conaws](https://github.com/Conaws) that I was thinking of writing a keyboard shortcuts extension, he recommended contributing to roam-toolkit.

I went ahead and started my own codebase because most of the code is copy-modified from my [todoist-shortcuts](https://github.com/mgsloan/todoist-shortcuts) extension.  So I just needed to adapt it to Roam's DOM which took me a fraction of the time it'd take me to implement the same thing within the conventions of roam-toolkit.

The two extensions can be used just fine simultaneously.  However, I would still be keen to add roam-navigator directly to roam-toolkit.  This would have quite a few beenefits:

* Fewer extensions for Roam users to install.

* We could get this functionality out to the folks already using roam-toolkit.

* Could use roam-toolkit's existing configuration code for settings.

* I wouldn't need to create an icon for roam-navigator.

I propose the following approach to this:

1. I'd open a PR adding `roam-navigator.js` + initial integration with roam-toolkit configuration.

2. Y'all would add direct commit access for me to roam-toolkit, with the understanding that I'd only do direct pushes to roam navigator code (and PRs for changes to other files in Roam Toolkit)

3. We'd plan to omit typescript annotations from the roam navigator code.  I could be swayed to include them, but I really like having a workflow where I can modify the code and have that immediately be reflected in the extension (no build step).  While I am a big fan of static types (esp powerful type systems like in Haskell), I actually don't think this variety of code benefits a whole lot.  Things pretty much work or not, manual testing can be pretty exhaustive as there isn't a whole lot of relevant variety in the execution state space.  Types certainly would help for documentation / collaboration, though.

4. Plan to not gate the PR on a big refactoring splitting it up or make the code more readable.  I know, some parts are a mess, but for me it's a familiar mess!  There is just [one big file](https://github.com/mgsloan/roam-navigator/blob/master/src/roam-navigator.js).  I think it's more valuable to polish the outward behavior than the inner beauty of this variety of code.

What do you think?  No problem at all if you'd rather keep the two separate, I actually wouldn't mind that, because:

* I think the name "roam navigator" is rad.  Astrolabes (roam logo) can be used in navigation.

* It's fun to watch extension user count rise.

* I could have my own sponsor link to [my buymeacoffee page](https://www.buymeacoffee.com/mgsloan).

For me what really counts is getting this functionality into people's hands, though, so overall I am more keen on including it in roam-toolkit.

**Comment by Stvad** [comment]
Hey @mgsloan, is there a demo of the current functionality of `roam-navigator`? From your description and the screenshot it sounds like what you're doing has a lot of overlap with #63 (have you seen that one btw?)

**Comment by mgsloan** [comment]
There is not a video or anything like that, but it can be directly loaded as an unpacked extension from the `src/` dir.  I hadn't seen #63, but it is a very different variety of navigation, certainly with some overlap.  That extension appears to be intent on adding relative / sequential navigation.

This variety of navigation is more akin to ace / avy jump mode in emacs, or vimium `f` link clicking.  In particular, the only keyboard shortcut you need to remember is `g` or `alt-g` to enter navigation mode, and then after that everything is visual.

**Comment by Stvad** [comment]
I see, so the relevant analogy would be https://github.com/tntmarket/vimmyroam ? (by @tntmarket again). Also related: I have some configs for Surfingkeys that make it work well with Roam (see in https://github.com/tntmarket/vimmyroam/issues/1)

**Comment by mgsloan** [comment]
Just watched the video, that's super cool!  I definitely am not intending to add block-level manipulations to Roam Navigator, really I just filled in the gaps for my workflows that are not met by Roam's default shortcuts.  Certainly Roam Navigator could integrate with the vim style shortcuts by creating a block selection / entering into normal mode instead of initiating text editing.

**Comment by mgsloan** [comment]
Yes, it's similar-ish to vimmyroam.  I did not know about vimmyroam or SurfingKeys, will check out the latter!  My analogy to ace-jump-mode is a bit flawed, since it doesn't really do a text search for the jump.  I might consider implementing that as a generic browser extension, as it's a fantastic way to navigate text.  Though, it may have trouble with plain input widgets, not sure if you can interoggate the browser for info about the visual location of different characters.

Here are the main things it has that the generic link selecting things do not:

1. Uses stable assignment of key sequences to your starred pages (modulo the extension reserving more prefixes)

2. Has a stable binding for selecting the last bullet in your note

3. You can select left sidebar entries even when it is collapsed, by using these stable sequences.

4. Has a binding for opening the closed sidebar, which requires a hover event rather than click

5. Bindings for scrolling both the main document and sidebar

6. Intelligent persistence of navigation mode - when you select a page link navigation mode continues.  When you select a block, navigation mode ends.

**Comment by mgsloan** [comment]
Also, I plan to add plain old link clicking too, probably by having a prefix of `l` in the visual navigation hint, followed by a sequence of keys that prioritizes homerow keys.  That's definitely a big omission right now, considering they're the primary bit of Roam's magic

**Comment by Stvad** [comment]
upon reflection - I don't think this will work under conditions you've described.  
What you're proposing is basically merging in the codebase you've created into the toolkit but designating it as a separate domain that only you understand. That does not seem like a workable approach to me tbh.  

I can see potential value in more tailored hint navigation integration for Roam in general (my current approach is to combine Surfingkeys and the RoamToolkit vim mode which works but can be improved)   
And some UX ideas you describe sound great!
But if we build it for the toolkit it should be done in synergy with existing work on vim mode and other parts of the extension. 

@tntmarket fyi

**Comment by Stvad** [comment]
>We'd plan to omit typescript annotations from the roam navigator code. I could be swayed to include them, but I really like having a workflow where I can modify the code and have that immediately be reflected in the extension

fyi the `npm run watch` mode with autobuild/reload works really well

**Comment by mgsloan** [comment]
> a separate domain that only you understand.

Yes separate domain, but not that only I understand.  The code is messy, but not unintelligible.  It has some comments, and most things are straightforward.  Right now my estimation of the expected benefits of rewriting it is far outweighed by the cost of doing so.  This might change if it becomes popular / if potential collaborators express that the structure is a roadblock to enhancements.  But that is quite uncertain, and so it is more efficient to hack something together.

> upon reflection - I don't think this will work under conditions you've described

Makes sense!  I picked out an icon and have published it as an independent extension.  Feel free to revisit this decision in the future if info changes.

> But if we build it for the toolkit it should be done in synergy with existing work on vim mode and other parts of the extension.

I haven't been able to build the vim branch successfully, but I don't see any a-priori reason that the vim mode would conflict with this extension.  Maybe a little weird to have two different link hinting systems.

I certainly look forward to the vim bindings, particularly the `o` and `shift+o` bindings.  i will try to make the extension synergistic with that once the vim bindings are released.  Part of the motivation of inclusion of roam-navigator would be such synergy, but it can probably be managed without sharing a repo.

> fyi the npm run watch mode with autobuild/reload works really well

Good to know!  My experiences in the past with npm have been uhh "varied", to put it politely.  Perhaps it's from not putting in the time to learn how to use it.  So far I only write javascript for browser extensions, most of my clientside work has been transpiled from Haskell.
